### PR TITLE
Minor UI changes

### PR DESCRIPTION
**Pull request by crowning-**
See screenshots attached to the requests.

### CODE REVIEW

**Comment by vertoe** [comment]
:+1: 

@crowning- in addition, do you have time to look into some overview glitches on the darksend panel? (cut off strings, static button sizes, etc.)

**Comment by crowning-** [comment]
Not today (have to travel tomorrow), but I can have a look tomorrow evening.

**Comment by crowning-** [comment]
...but I have no idea what you mean with "static button sizes".

Anyway, merge this ones first so the translators can test with different locales. I'm pretty sure some languages will break the layout again so we'll have to re-fix.

**Comment by vertoe** [comment]
maybe switch to german and check out this screenshot:
the buttons are static size, they could use more width, maybe some relative value.

screenshot-3

and by the way, please close this PR and issue it agains branch v0.11.1.x

**Comment by crowning-** [comment]
Just build a German test box, and yes, the German wallet looks even worse :-/

I'll take care of that tomorrow.

I'll leave this PR open for reference now.

**Comment by crowning-** [comment]
Did stuff in the v0.11.1.x branch.

**Pull request closed without merging**
