### PR TITLE
fix: hpmn registration after revocation caused mining failure

### PR DESCRIPTION
**Pull request by PastaPastaPasta**
## Issue being fixed or feature implemented
We reset operator info on revocation; but then on replacement via new register we try to "RemoveMN", which tries to remove platformNodeID but that's already been cleared

## What was done?
Only try to delete platformNodeID if it's non-null

## How Has This Been Tested?
Mined with it on testnet; mining works

## Breaking Changes
This will fork off other testnet nodes, as this fixes the logic

## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [x] I have assigned this pull request to a milestone

### CODE REVIEW

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
>which tries to remove platformNodeID but that's already been cleared

So basically it tries to remove a _null_ `platformNodeID` which was never added in the first place (because `UpdateUniqueProperty` won't let you). Makes sense I guess cause a null `platformNodeID` should never be considered unique, that's clearly a bug. We should never try to add it via `AddUniqueProperty` in `AddMN` either... pls fix it with a similar patch while we are at it.

**Comment by ogabrielides** [comment]
> > which tries to remove platformNodeID but that's already been cleared
> 
> So basically it tries to remove a _null_ `platformNodeID` which was never added in the first place (because `UpdateUniqueProperty` won't let you). Makes sense I guess cause a null `platformNodeID` should never be considered unique, that's clearly a bug. We should never try to add it via `AddUniqueProperty` in `AddMN` either... pls fix it with a similar patch while we are at it.

In Testnet, a HPMN was revoked (hence setting the `platformNodeID`) and then a new HPMN registration with the already used (revoked) collateral.

**Comment by ogabrielides** [comment]
@UdjinM6 Added the check in AddMN as well (although it should never happen as explained above)

**Review by UdjinM6 — APPROVED** [review]
utACK

**Review by ogabrielides — APPROVED** [review]
LGTM

**Pull request merged**
