### PR TITLE
extract_strings_qt.py should generate strings for darkcoin-core

### PR DESCRIPTION
**Pull request by UdjinM6**

### CODE REVIEW

**Comment by vertoe** [comment]
Ahhh!

**Comment by vertoe** [comment]
Updating 'src/qt/locale/darkcoin_en.ts'...
    Found 255 source text(s) (12 new and 243 already existing)

Where did you find the 800+ strings again? Qt Linguist?

**Comment by UdjinM6** [comment]
Hmmm... first this one and then in Qt Creator I did "Tools" -> "External" -> "Linguist" -> "Update Translations (lupdate)"
Now I have ```Updating 'src/qt/locale/darkcoin_en.ts'...
    Found 908 source text(s) (0 new and 908 already existing)```
Here it is http://pastebin.com/EEFBLs06

**Comment by vertoe** [comment]
Prefect, I just checked these strings: http://pastebin.com/EEFBLs06
It's including everything I've seen missing. Will update it for transifex. 
I use the pastebin file ok? Not using Qt Creator currently.

**Comment by UdjinM6** [comment]
@vertoe yep, this should be ok I guess. Can you update ru too?)) http://pastebin.com/sG5ecaY0

**Comment by vertoe** [comment]
@UdjinM6 yeah just use `tx push -t -l ru` to push a translation (guess you already did that) and `tx push -s` to push the english source file.

**Pull request merged**
