### PR TITLE
Added link to Transifex translation site for missing languages

### PR DESCRIPTION
**Pull request by crowning-**
I guess it doesn't make sense to translate this one :-)

optionsdialog

### CODE REVIEW

**Comment by vertoe** [comment]
Hi, cool move! :+1: 

Can we have some native english speaker to reword this a little bit? "Language missing or translation incomplete? Help contributing translations here: https://..."

And please remove the brackets ;)

**Comment by crowning-** [comment]
Commited an update to patch-2, looks like this now:
optionsdialog

**Comment by evan82** [comment]
great idea!

**Comment by vertoe** [comment]
@crowning- is there a specific reason why this has the flag `<string notr="true">` ?

**Comment by crowning-** [comment]
@vertoe : yes...if a language does not exist it will be displayed in English anyway :-)

I can change this for the cases when a) a language partially exists **AND** b) this string _is_ already translated to that language, though.

You decide..

**Pull request merged**
