### PR TITLE
Complete russian, spanish and german translation

### PR DESCRIPTION
**Pull request by vertoe**
Thanks to @udjinm6 we already have a complete russian translation. To be used to identify untranslated strings. Will be helpful to have this included when instantx testing is started.

Will from now on only push translations once a week (or once a month if things settle down).

### CODE REVIEW

**Comment by vertoe** [comment]
Ok cool I was able to merge in the existing strings from bitcoin core in 72 languages \yay/

**Comment by vertoe** [comment]
Spanish finished, too.

**Comment by vertoe** [comment]
And german is finished, too.

**Comment by evan82** [comment]
Awesome

**Pull request merged**
