### PR TITLE
ci: bump docker and docker-dind to 20.10.20 for gitlab

### PR DESCRIPTION
**Pull request by kwvg**
## Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

### CODE REVIEW

**Comment by PastaPastaPasta** [comment]
why?

**Comment by PastaPastaPasta** [comment]
I don't think this makes senes. Looks like 9.5.0 of gcc has the bug fix also. I really don't think we should upgrade to ubuntu 22.04 at this point.

**Comment by PastaPastaPasta** [comment]
What commit introduces the buggy code?

**Comment by PastaPastaPasta** [comment]
Are there alternative fixes? maybe by changing how we initialize these requests? How did bitcoin-core avoid this buggy compiler code?

**Review by strophy — DISMISSED** [review]
utACK, let's try it and see if it works. Manager node might need upgrading.

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
blocking this with a "request changes" review to  make sure it's not merged prior to #5068 (or any alternative PR) which fixes CI failures introduced by these changes

**Review by strophy — APPROVED** [review]
:+1:

**Comment by PastaPastaPasta** [comment]
CI is currently failing... Rebasing to see if that helps for some reason https://gitlab.com/dashpay/dash/-/jobs/3256133934

**Review by UdjinM6 — APPROVED** [review]
utACK

**Pull request merged**
