### PR TITLE
Rebrand to darkcoin

### PR DESCRIPTION
**Pull request by vertoe**
darkcoinstrings.cpp
darkcoin.qrc
darkcoin-config.h
darkcoind-res.rc
darkcoin-cli-res.rc
darkcoin-qt-res.rc

### CODE REVIEW

**Comment by vertoe** [comment]
Includes translations by design.

**Comment by vertoe** [comment]
and a version bump to 0.11.2.0

**Comment by vertoe** [comment]
Nevermind, I squeezed the copyright note in one line.

**Comment by UdjinM6** [comment]
:+1: (but not tested as I have no windows here too :) )

**Comment by evan82** [comment]
This broke compiling so I reverted it:

11:23:30 {v0.11.2.x} ~/Desktop/darkcoin$ make -j9
 /bin/bash ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating src/test/Makefile
config.status: creating src/qt/Makefile
config.status: creating src/qt/test/Makefile
config.status: creating share/setup.nsi
config.status: creating share/qt/Info.plist
config.status: creating qa/pull-tester/run-bitcoind-for-test.sh
config.status: creating qa/pull-tester/build-tests.sh
config.status: error: cannot find input file: `src/darkcoin-config.h.in'
make: *** [Makefile] Error 1

**Comment by evan82** [comment]
**Nevermind! I just didn't compile it correctly**

**Pull request merged**
